GarronT.CMS.UI/Areas/Admin/Controllers/InstallerAllocationController.cs
using GarronT.CMS.Model;
using GarronT.CMS.Model.BO;
using GarronT.CMS.Model.DAL;
using KSPL.Indus.MSTS.UI.Filters;
using OfficeOpenXml;
//using OfficeOpenXml;
using System;
using System.Collections.Generic;

using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Device.Location;
using System.Threading.Tasks;
using log4net;
using Microsoft.AspNet.Identity;
using GarronT.CMS.UI.CustomHelpers;
using GarronT.CMS.Model;

namespace GarronT.CMS.UI.Areas.Admin.Controllers
{
    [OutputCache(Duration = 0, VaryByParam = "none")]
    [SessionExpire]
    [Authorize]
    [RBAC]
    public class InstallerAllocationController : Controller
    {
        #region Create Object ILog for Logger write
        private static readonly ILog log = LogManager.GetLogger(typeof(clsMail));
        #endregion
        public class Address
        {
            public int id
            {
                get;
                set;
            }
        }
        public ActionResult Index()
        {
            return base.View();
        }
        public ActionResult Index1()
        {
            return base.View();
        }
        public ActionResult GetPoject()
        {
            ProjectMasterDAL projectMasterDAL = new ProjectMasterDAL();
            IEnumerable<ProjectModel> data = (from a in projectMasterDAL.GetProjectName()
                                              orderby a.ProjectName
                                              select a).Distinct<ProjectModel>();
            var checkAdmin = Session["CurrentUserIsAdmin"].ToString();

            if (checkAdmin == "0")
            {
                var userId = new UserDetails().GetUserId(User.Identity.GetUserId());
                var abcd = new ProjectMasterDAL().GetUserProjectList(userId);


                if (abcd == null || abcd.Count == 0)
                {
                    if (data != null && data.Count() > 0)
                    {
                        data = data.Take(0).ToList();
                    }
                }
                else
                {
                    if (data != null && data.Count() > 0)
                    {
                        data = data.Where(o => abcd.Contains(o.ProjectId)).ToList();
                    }
                }

            }

            return base.Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getRowPartial()
        {
            return base.PartialView("Partial_InstallerAllocation");
        }

        public JsonResult GetAddress(List<string> Root, List<string> Cycle, List<string> Address, long ProjectID, string installerId, string fromDate, string toDate)
        {
            try
            {
                List<AddressMaster> installerAddress = new List<AddressMaster>();
                List<AddressMaster> list = new List<AddressMaster>();

                list = new InstallerDAL().GetDynamicAllAddress(Root, Cycle, ProjectID);

                if (!string.IsNullOrEmpty(installerId)) 
                {
                    // get existing mapped records.
                    installerAddress = new InstallerDAL().GetDynamicInstallerExistingAddress(ProjectID, Root, Cycle, fromDate, toDate, long.Parse(installerId));

                    if (list != null && list.Count > 0 && Address != null && Address.Count > 0)
                    {
                        var tempData = list.Where(o => Address.Contains(o.ID.ToString())).Select(o => new AddressMaster
                        {
                            Latitude = o.Latitude,
                            Longitude = o.Longitude,
                            ID = o.ID,
                            Street = o.Street,
                            Cycle = o.Cycle,
                            Route = o.Route
                        }).ToList();

                        foreach (var item in tempData)
                        {
                            var checkPresent = installerAddress.Where(o => o.ID == item.ID).Count();
                            if (checkPresent == 0)
                            {
                                installerAddress.Add(item);
                            }
                        }
                    }

                }
                if ((list == null || list.Count == 0) && (installerAddress != null || installerAddress.Count > 0))
                {
                    list = installerAddress;
                }
                else
                {
                    if (installerAddress != null)
                    {
                        list.AddRange(installerAddress);
                        list = list.OrderBy(a => a.Latitude).ThenBy(a => a.Longitude).ThenBy(a => a.Street).ToList();
                    }
                }


                JsonResult jsonResult = base.Json(new
                {
                    AllAddress = list,
                    InstallerAddress = installerAddress
                }, JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = new int?(2147483647);
                return jsonResult;
            }
            catch (Exception ex)
            {

                // throw;
                log.Info("InstallerAllocation  GetAddress ERROR at " + DateTime.Now.ToString());
                log.Info("ERROR  ex.Message - " + (ex.Message != null ? ex.Message : ""));
                log.Info("ERROR  ex.StackTrace - " + (ex.StackTrace != null ? ex.StackTrace : ""));
                log.Info("ERROR  ex.InnerException.Message - " + (ex.InnerException.Message != null ? ex.InnerException.Message : ""));


                return base.Json(new { success = false, message = "Server error." }, JsonRequestBehavior.AllowGet);
            }

        }

        [HttpGet]
        public JsonResult getCurrentInstallerList(long projectId)
        {
            List<UsersSmallModel> obj1 = new List<UsersSmallModel>();
            if (projectId > 0)
            {
                using (UserRoleDAL obj = new UserRoleDAL())
                {
                    obj1 = obj.GeInstallerListCurrentProject(projectId).OrderBy(a => a.UserName).ToList();
                }
            }

            return Json(obj1, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetFreshCycles(long projectID)
        {
            List<string> cyclelist = new List<string>();

            //cyclelist = new InstallerDAL().GetFreshCycleByProjectID(projectID);
            cyclelist = new InstallerDAL().GetDynamicFreshCycleByProjectID(projectID);

            return base.Json(cyclelist, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetExistingCycles(long projectID, long installerId, string fromDate, string toDate)
        {
            List<string> cyclelist1 = new List<string>();

            cyclelist1 = new InstallerDAL().GetDynamicFreshCycleByProjectID(projectID);



            var cyclelist2 = new InstallerDAL().GetDynamicExistingMappedCycle(projectID, installerId, DateTime.Parse(fromDate), DateTime.Parse(toDate));


            List<CycleMaster> OrignalCycleList = new List<CycleMaster>();
            List<CycleMaster> cyclelist = new List<CycleMaster>();
            foreach (var item in cyclelist1)
            {
                OrignalCycleList.Add(new CycleMaster { CycleId = item, CycleDisabled = false });
            }


            foreach (var item in cyclelist2)
            {
                var ObjCycle = OrignalCycleList.Where(o => o.CycleId == item.Cycle).FirstOrDefault();
                if (ObjCycle == null)
                {
                    OrignalCycleList.Add(new CycleMaster { CycleId = item.Cycle, CycleDisabled = item.Disabled == 0 ? false : true });
                }
                else
                {

                    if (ObjCycle.CycleDisabled == false)
                    {
                        ObjCycle.CycleDisabled = item.Disabled == 0 ? false : true;
                    }
                }
            }

            foreach (var item in cyclelist2)
            {
                var ObjCycle = cyclelist.Where(o => o.CycleId == item.Cycle).FirstOrDefault();
                if (ObjCycle == null)
                {
                    cyclelist.Add(new CycleMaster { CycleId = item.Cycle, CycleDisabled = item.Disabled == 0 ? false : true });
                }
                else
                {

                    if (ObjCycle.CycleDisabled == false)
                    {
                        ObjCycle.CycleDisabled = item.Disabled == 0 ? false : true;
                    }
                }
            }

            cyclelist = cyclelist.OrderBy(o => o.CycleId).Distinct().ToList();
            OrignalCycleList = OrignalCycleList.OrderBy(o => o.CycleId).Distinct().ToList();
            return base.Json(new { OrignalCycleList = OrignalCycleList, CycleList = cyclelist }, JsonRequestBehavior.AllowGet);
        }



        public ActionResult GetRootByCycle(long ProjectId, string[] Cycle, string InstallerId, string strDateTime, string strtoTime)
        {


            List<string> routeList = new InstallerDAL().GetDynamicFreshRootByCycle(Cycle, ProjectId);

            List<PROC_ExistingRoute_Result> ObjExistingList = new InstallerDAL().GetDynamicExistingRootByCycle(Cycle, ProjectId, long.Parse(InstallerId), DateTime.Parse(strDateTime), DateTime.Parse(strtoTime));


            if (routeList == null)
            {
                routeList = new List<string>();
            }

            foreach (var item in ObjExistingList)
            {
                var checkRoutePresent = routeList.Where(o => o == item.Route).FirstOrDefault();
                if (checkRoutePresent == null)
                {
                    routeList.Add(item.Route);
                }
            }

            var InstallerRouteList = new List<RouteMaster>();

            foreach (var item in ObjExistingList)
            {

GarronT.CMS.UI/Areas/Admin/Views/InstallerAllocation/Index1.cshtml
@model GarronT.CMS.Model.BO.ProjectModel

@{
    ViewBag.Title = "Appointment";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@Html.Hidden("urlGetProject", Url.Action("GetPoject", "InstallerAllocation"))
@Html.Hidden("getRowPartial", Url.Action("getRowPartial", "InstallerAllocation"))
@Html.Hidden("GetAddressUrl", Url.Action("GetAddress", "InstallerAllocation"))
@Html.Hidden("GetCycle", Url.Action("GetExcelRootData", "InstallerAllocation"))
@Html.Hidden("GetRootByCycle", Url.Action("GetRootByCycle", "InstallerAllocation"))
@Html.Hidden("GetAddress", Url.Action("GetAddressByCycle_Root", "InstallerAllocation"))
@Html.Hidden("GetLatLag", Url.Action("GetLat_by_Root", "InstallerAllocation"))
@Html.Hidden("urlGetInstallerList", Url.Action("getCurrentInstallerList", "Project"))
@Html.Hidden("urlSaveInstallerMap", Url.Action("SaveInstallerMap", "InstallerAllocation"))
@Html.Hidden("urlGetInstallerMap", Url.Action("GetInstallerMap", "InstallerAllocation"))
@Html.Hidden("GetLatLagby_ProjectInstaller", Url.Action("GetLat_by_ProjectInstaller", "InstallerAllocation"))
@Html.Hidden("UrlDashboard", Url.Action("Index", "Dashboard"))

<script>
    $(function () {
        //$("#datepicker").datepicker();
    });
</script>

<style type="text/css">
    .list {
        background-color: lightblue;
    }

    #items .ui-selected {
        background: red;
        color: white;
        font-weight: bold;
    }

    #items .ui-selecting {
        background: #ffd800;
        color: white;
        font-weight: bold;
    }


    #items {
        list-style-type: none;
        margin: 0;
        padding: 0;
        width: 100px;
    }

        #items li {
            margin: 2px;
            padding: 2px;
        }
</style>

<script type="text/javascript">
    //$("#datepicker").datepicker({
    //    buttonImage: '...images/DatePicker_icon.png',
    //    buttonImageOnly: true,
    //    changeMonth: true,
    //    changeYear: true,
    //    showOn: 'both',
    //}); </script>
@*<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=&sensor=false"> </script>*@
@{
    var href = "https://maps.googleapis.com/maps/api/js?key=" + System.Configuration.ConfigurationManager.AppSettings["googleapiKey"].ToString() + "&sensor=false";
}
<script type="text/javascript" src="@href"></script>

<div id="loading"> <div id="loadingcontent"> <p id="loadingspinner"> Searching things... </p> </div> </div>
<style>
    .toast-top-center {
        margin-top: -50px;
    }
</style>
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12" id="m">
                <section class="panel">
                    @*<header class="panel-heading">
                        <b>Installer Allocation </b>

                        </header>*@



                    <div class="row" style="margin-top:20px;">
                        <div class="col-lg-12">
                            <section class="panel">
                                <header class="panel-heading" style="background: #80B2DF; color: #fff;">
                                    Installer Allocation
                                    <span class="tools pull-right">
                                        <a id="haha" class="fa fa-chevron-down clickdive" href="javascript:;" style="color: #fff; padding-right:10px;"></a>

                                    </span>
                                </header>
                                <div class="panel-body" style="padding-top:20px;">
                                    <form id="InstallerAllocationForm">

                                        <div class="row">
                                            <div class="form-group col-lg-4">

                                                <label class="col-lg-8" for=" name">Date</label>

                                                @*<input type="text" name="Date" id="Date" class="inputclass form-control" />@*<img src="~/images/DatePicker_icon.png" width="20px" hight="20px" />*@

                                                <input type="text" name="Dates" id="datepicker" readonly='true' class="form-control col-lg-3" />


                                            </div>

                                            <div class="form-group col-lg-4">

                                                <label for="name"> Project <span style="color:red">*</span></label>


                                                <select id="ddlProject" class="form-control" name="ProjectName"></select>
                                            </div>


                                            <div class="form-group col-lg-4">

                                                <label for="name">Installer <span style="color:red">*</span></label>

                                                <select id="ddlInstaller" class="form-control" name="Installer"></select>
                                            </div>



                                        </div>

                                        <div class="row">

                                            <div class="form-group col-lg-4">

                                                <label> Cycle &nbsp; </label>
                                                <div id="divcycle">
                                                    <input type="text" onkeyup="filter(this)" />

                                                    <ul id="items">
                                                        <li class="list" value="11">Item 11</li>
                                                        <li class="list" value="12">Item 12</li>
                                                        <li class="list" value="13">Item 13</li>
                                                        <li class="list" value="14">Item 4</li>
                                                        <li class="list" value="15">Item 5</li>
                                                        <li class="list" value="16">Item 16</li>
                                                        <li class="list" value="17">Item 17</li>
                                                        <li class="list" value="18">Item 18</li>
                                                        <li class="list" value="19">Item 9</li>
                                                        <li class="list" value="20">Item 10</li>
                                                    </ul>
                                                    @*<select id="ddlCycle" name="Cycle" class="form-control" style="display:none;" multiple="multiple"></select>*@
                                                </div>
                                            </div>


                                            <div class="form-group col-lg-4">

                                                <label> Route &nbsp; </label>
                                                <div id="divroot">
                                                    <select id="ddlRoot" name="Root" class="form-control" multiple="multiple"></select>

                                                </div>
                                            </div>



                                            <div class="form-group col-lg-4">
                                                <label> Address &nbsp; </label>
                                                <div id="divaddress">
                                                    <select id="ddlAddress" class="form-control" name="Address" multiple="multiple"></select>
                                                </div>
                                            </div>

                                        </div>



                                        <br />
                                        <br />
                                        <div class="form-group">

                                            <div class="col-lg-12" style="text-align:center">
                                                @*<input type="submit" class="btn btn-success" value="Add" onclick="" />*@
                                                <button id="btnShowMap" class="btn btn-success" type="button">Show Map</button>
                                                <button id="btnSave" class="btn btn-success" type="button">Save</button>
                                                <button class="btn btn-danger" id="btnCancel" type="button">Cancel</button>
                                                <button class="btn btn-default" id="btnReset" type="button">Reset</button>
                                            </div>
                                            <br />
                                        </div>

                                </div>
                                </form>
                        </div>
                </section>
            </div>
        </div>

        <div class="row">

            <div class="col-lg-12" id="LoadRow" style="height: 100% ; width: 95%; bottom: 0px;">

            </div>

        </div>
    </section>
    </div>
    </div>
</section>



</section>

<script src='@Url.Content("~/Scripts/Admin/InstallerAllocation.js")'></script>


@*<link href="~/Scripts/js/style.css" rel="stylesheet" />
    <link href="~/Scripts/js/jquery-ui.css" rel="stylesheet" />
    <script src="~/Scripts/js/jquery-ui.js"></script>
    <script src="~/Scripts/js/fieldChooser.js"></script>
    <link href="~/Content/MSTS/admin/css/bootstrap-multiselect.css" rel="stylesheet" />
    <script src="~/Content/MSTS/admin/js/bootstrap-multiselect.js"></script>
    <script src="~/Scripts/Admin/InstallerAllocation.js"></script>*@


<link rel="stylesheet" href="https://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
<script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
<script type="text/javascript" src="https://www.pureexample.com/js/lib/jquery.ui.touch-punch.min.js"></script>


<script>
    $(document).ready(function () {
        $("#items").selectable({
            start: function (event, ui) {

                $('#items').trigger('unselected')
                $('#items li').removeClass('click-selected');
                $(ui.unselected).removeClass('click-selected');
            },
            selected: function (event, ui) {
                debugger;
                if ($(ui.selected).hasClass('click-selected')) {
                    $(ui.selected).removeClass('ui-selected click-selected');

                } else {
                    $(ui.selected).addClass('click-selected');

                }
            },
            unselected: function (event, ui) {
                debugger;
                $(ui.unselected).removeClass('click-selected');
            },
            stop: function (event, ui) {
                debugger;
                $(".ui-selected", this).each(function () {
                    debugger;
                    alert(this.value)
                });
            }
        });
    })
    function filter(element) {
        var value = $(element).val();

        $("#items > li").each(function () {
            if ($(this).text().search(value) > -1) {
                $(this).show();
            }
            else {
                $(this).hide();
            }
        });
    }
</script>

GarronT.CMS.UI/Areas/Admin/Views/InstallerAllocation/Partial_InstallerAllocation.cshtml
<div id="map_canvas" class="col-lg-12" style="height: 100%; width:100%; ">

</div>