GarronT.CMS.UI/Areas/Admin/Controllers/FormController.cs
using GarronT.CMS.Model;
using GarronT.CMS.Model.BO;
using GarronT.CMS.Model.DAL;
using KSPL.Indus.MSTS.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GarronT.CMS.UI.Areas.Admin.Controllers
{
     [SessionExpire]
     [Authorize]
     [RBAC]
    public class FormController : Controller
    {
        //
        // GET: /Admin/Form/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult getPreviousRecordsPartial()
        {
            return PartialView("_FormHome");
        }

        public ActionResult getFormPartial()
        {
            return PartialView("_AddNewForm");
        }



        public ActionResult get_setField1Partial()
        {
            return PartialView("_setField1");
        }


        public ActionResult GetProjectList()
        {
            List<ProjectModel> objList1 = new List<ProjectModel>();
            using (ProjectMasterDAL obj = new ProjectMasterDAL())
            {
                objList1 = obj.GetProjectName();
            }

            return Json(objList1, JsonRequestBehavior.AllowGet);
        }



        public ActionResult GetDynamicDivData(long ProjectId)
        {

            List<VW_GETTab6DropdownData> objData = new List<VW_GETTab6DropdownData>();
            using (ProjectMasterDAL obj = new ProjectMasterDAL())
            {
                objData = obj.GetViewData(ProjectId);
               
            }


            string s = "<div id='fieldDiv1' name='textField' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>ACCOUNT</div>" +
                "<div id='fieldDiv2' name='textField' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>STREET</div>" +
                "<div id='fieldDiv3' name='textField' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>OLD METER NUMBER</div>" +
                "<div id='fieldDiv4' name='textField' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>OLD METER SIZE</div>" +
                "<div id='fieldDiv5' name='textField' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>OLD METER TYPE</div>";
                //"<div id='fieldDiv8' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>OLD METER RADIO NO</div>" +
                //"<div id='fieldDiv9' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>OLD METER READING</div>" +
                //"<div id='fieldDiv10' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>NEW METER NUMBER</div>" +
                //"<div id='fieldDiv11' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>NEW REGISTER NUMBER</div>" +
                //"<div id='fieldDiv12' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>NEW METER RADIO</div>" +
                //"<div id='fieldDiv13' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>NEW METER SIZE</div>" +
                //"<div id='fieldDiv14' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>NEW METER TYPE</div>" +
                //"<div id='fieldDiv18' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>SERVICES</div>" +
                //"<div id='fieldDiv19' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>COMMENTS</div>" +
                //"<div id='fieldDiv20' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>Customer Pin</div>" +
                //"<div id='fieldDiv21' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>Customer Name</div>" +
                //"<div id='fieldDiv22' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>Customer Address</div>" +
                //"<div id='fieldDiv23' class='nextBtn' style='min-width: 80% !important; margin-bottom: 0px; float:none;'>Customer Pin</div>";

            return Json(objData, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Returns form list
        /// </summary>
        /// <param name="Status">1=> active , 0=> Deactive </param>
        /// <returns></returns>
        public ActionResult GetFormList(bool Status)
        {

            List<FormDOL> objList1 = new List<FormDOL>();
            using (FormDAL obj = new FormDAL())
            {
                objList1 = obj.GetFormList(Status);
            }

            return Json(objList1, JsonRequestBehavior.AllowGet);
        }


        /// <summary>
        /// Tab 5 - Deactivates the custom field
        /// </summary>
        /// <param name="customFieldId"></param>
        /// <returns>true if successful</returns>
        public ActionResult A_Or_D_FormRecord(bool status, long FormId)
        {
            using (FormDAL obj = new FormDAL())
            {
                string result;
                int userId = 1;
                bool a = obj.A_Or_D_FormRecord(status, FormId, userId, out result);
                return Json(new { success = a, returnMessage = result }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// Tab 5 - Activates the deactivated record of custom field
        /// </summary>
        /// <param name="customFieldId"></param>
        /// <returns>true if successful</returns>
        public ActionResult ActivateCustomFieldRecord(long customFieldId)
        {
            ProjectMasterDAL obj = new ProjectMasterDAL();
            string result;
            int userId = 1;
            bool a = obj.ActivateCustomFieldRecord(customFieldId, userId, out result);
            return Json(new { success = a, returnMessage = result }, JsonRequestBehavior.AllowGet);
        }



    }
}

GarronT.CMS.UI/Areas/Admin/Controllers/StateController.cs
using GarronT.CMS.Model.BO;
using KSPL.Indus.MSTS.UI.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GarronT.CMS.UI.Areas.Admin.Controllers
{
    [OutputCache(Duration = 0, VaryByParam = "none")]
     [SessionExpire]
     [Authorize]
    [RBAC]
    public class StateController : Controller
    {
        // GET: Admin/State
        public ActionResult Index()
        {
            return View();
        }

        List<StateModel> list = new List<StateModel>();

        public ActionResult GetStateList()
        {

            StateModel obj1 = new StateModel();
            obj1.StateID = 1;
            obj1.CountryID = 1;
            obj1.CountryName = "US";
            obj1.StateName = "Alabama";
            list.Add(obj1);

            StateModel obj2 = new StateModel();
            obj2.StateID = 2;
            obj2.CountryID = 1;
            obj2.CountryName = "US";
            obj2.StateName = "Arizona";
            list.Add(obj2);

            StateModel obj3 = new StateModel();
            obj3.StateID = 3;
            obj3.CountryID = 1;
            obj3.CountryName = "US";
            obj3.StateName = "Mississippi"; 
            list.Add(obj3);

            StateModel obj4 = new StateModel();
            obj4.StateID = 4;
            obj4.CountryID = 1;
            obj4.CountryName = "US";
            obj4.StateName = "New York";
            list.Add(obj4);
            StateModel obj5 = new StateModel();
            obj5.StateID = 5;
            obj5.CountryID = 1;
            obj5.CountryName = "US";
            obj5.StateName = "Texas";
            list.Add(obj5);
            StateModel obj6 = new StateModel();
            obj6.StateID = 6;
            obj6.CountryID = 1;
            obj6.CountryName = "US";
            obj6.StateName = "Washington";
            list.Add(obj6);

            TempData["StateMasterList"] = list;
            return Json(list, JsonRequestBehavior.AllowGet);

        }


        public ActionResult Edit(long editId)
        {
            list = (List<StateModel>)TempData["StateMasterList"];
            StateModel obj1 = list.Where(o => o.StateID == editId).FirstOrDefault();
            TempData.Keep("StateMasterList");
            return Json(obj1, JsonRequestBehavior.AllowGet);

        }
    }
}

GarronT.CMS.UI/Areas/Form/Controllers/FormManagement1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GarronT.CMS.UI.Areas.Form.Controllers
{
    public class FormManagement1Controller : Controller
    {
        //
        // GET: /Form/FormManagement/
        public ActionResult Index()
        {
            return View();
        }
	}
}

GarronT.CMS.UI/Areas/Admin/Views/Form/Index.cshtml
@{
    ViewBag.Title = "Form";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@*@Html.Hidden("CountryListUrl", Url.Action("GetCountryList", "Country"))
    @Html.Hidden("StateByCoutryIDListUrl", Url.Action("GetStateListByCountryID", "State"))
    @Html.Hidden("urlEditData", Url.Action("Create", "State"))
    @Html.Hidden("UrlStateList", Url.Action("GetStateList", "State"))
    @Html.Hidden("urlDeleteData", Url.Action("Delete", "State"))
    @Html.Hidden("urlDeActiveRecords", Url.Action("GetDeActiveRecords", "State"))
    @Html.Hidden("urlGetData", Url.Action("Edit", "State"))*@
@Html.Hidden("getPreviousRecordsPartial", Url.Action("getPreviousRecordsPartial", "Form"))
@Html.Hidden("getFormPartial", Url.Action("getFormPartial", "Form"))
@Html.Hidden("get_setField1Partial", Url.Action("get_setField1Partial", "Form"))
@Html.Hidden("GetProjectList", Url.Action("GetProjectList", "Form"))
@Html.Hidden("GetDynamicDivData", Url.Action("GetDynamicDivData", "Form"))
@Html.Hidden("GetFormListURL", Url.Action("GetFormList", "Form"))
@Html.Hidden("A_Or_D_FormRecordURL", Url.Action("A_Or_D_FormRecord", "Form"))

<style>
    .toast-top-center {
        margin-top: -50px;
    }
</style>

<div id="loading">
    <div id="loadingcontent">
        <p id="loadingspinner">
            Searching things...
        </p>
    </div>
</div>



<!-- page start-->


<section id="main-content">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading" style="padding-top:5px;">
                        <b>Form Management </b>

                    </header>
                    <div class="panel-body" id="divLandingPage" style="padding-top:10px;">
                        <div class="panel-body">



                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
</section>


<link href="~/Scripts/js/style.css" rel="stylesheet" />
<link href="~/Scripts/js/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/js/jquery-ui.js"></script>
<script src="~/Scripts/js/fieldChooser.js"></script>


<link href="~/Content/MSTS/admin/css/bootstrap-multiselect.css" rel="stylesheet" />
<script src="~/Content/MSTS/admin/js/bootstrap-multiselect.js"></script>

<script src="~/Scripts/Admin/FormManagement.js"></script>

GarronT.CMS.UI/Areas/Admin/Views/Form/Index2.cshtml
@{
    ViewBag.Title = "Form";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@*@Html.Hidden("CountryListUrl", Url.Action("GetCountryList", "Country"))
    @Html.Hidden("StateByCoutryIDListUrl", Url.Action("GetStateListByCountryID", "State"))
    @Html.Hidden("urlEditData", Url.Action("Create", "State"))
    @Html.Hidden("UrlStateList", Url.Action("GetStateList", "State"))
    @Html.Hidden("urlDeleteData", Url.Action("Delete", "State"))
    @Html.Hidden("urlDeActiveRecords", Url.Action("GetDeActiveRecords", "State"))
    @Html.Hidden("urlGetData", Url.Action("Edit", "State"))*@
@Html.Hidden("getPreviousRecordsPartial", Url.Action("getPreviousRecordsPartial", "Form"))
@Html.Hidden("getFormPartial", Url.Action("getFormPartial", "Form"))
@Html.Hidden("get_setField1Partial", Url.Action("get_setField1Partial", "Form"))
@Html.Hidden("GetProjectList", Url.Action("GetProjectList", "Form"))
@Html.Hidden("GetDynamicDivData", Url.Action("GetDynamicDivData", "Form"))
@Html.Hidden("GetFormListURL", Url.Action("GetFormList", "Form"))
@Html.Hidden("A_Or_D_FormRecordURL", Url.Action("A_Or_D_FormRecord", "Form"))

<style>
    .toast-top-center {
        margin-top: -50px;
    }
</style>

<div id="loading">
    <div id="loadingcontent">
        <p id="loadingspinner">
            Searching things...
        </p>
    </div>
</div>



<!-- page start-->


<section id="main-content" ng-controller="CreateCtrl">
    <section class="wrapper">
        <!-- page start-->
        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading" style="padding-top:5px;">
                        <b>Form Management </b>

                    </header>
                    <div class="panel-body" id="divLandingPage" style="padding-top:10px;">

                    </div>
                </section>
            </div>
        </div>
    </section>
</section>
   

<link href="~/Scripts/js/style.css" rel="stylesheet" />
<link href="~/Scripts/js/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/js/jquery-ui.js"></script>
<script src="~/Scripts/js/fieldChooser.js"></script>


<link href="~/Content/MSTS/admin/css/bootstrap-multiselect.css" rel="stylesheet" />
<script src="~/Content/MSTS/admin/js/bootstrap-multiselect.js"></script>

<script src="~/Scripts/Admin/FormManagement.js"></script>

GarronT.CMS.UI/Areas/Admin/Views/Form/_AddNewForm.cshtml
<style type="text/css">
    .stepwizard-step p {
        margin-top: 10px;
    }

    .stepwizard-row {
        display: table-row;
    }

    .stepwizard {
        display: table;
        width: 100%;
        position: relative;
        background: #c0d7e5;
    }

    .stepwizard-step button[disabled] {
        opacity: 1 !important;
        filter: alpha(opacity=100) !important;
    }

    .stepwizard-row:before {
        top: 32px;
        bottom: 0;
        position: absolute;
        content: " ";
        width: 100%;
        height: 1px;
        background-color: #ccc;
        z-index: 0;
    }

    .stepwizard-step {
        display: table-cell;
        text-align: center;
        position: relative;
        width: 20%;
    }

    .btn-circle {
        width: 30px;
        height: 30px;
        text-align: center;
        padding: 6px 0;
        font-size: 12px;
        line-height: 1.428571429;
        border-radius: 15px;
    }

    .multiselect {
        width: 180px;
        padding: 3px;
    }
</style>
<div>
    <div class="form-group col-lg-6">
        <label for="name" class="col-lg-3">Project Name<span style="color:red">*</span></label>

        <select name="ddlProjectdropdown" id="ddlProject" class="col-lg-9"></select>

    </div>

    <div class="form-group col-lg-6">
        <label for="name" class="col-lg-3">Form Name<span style="color:red">*</span></label>

        <div class="col-lg-9">
            <input type="text" name="NewFormName" id="txtNewFormName" class=" form-control" />
        </div>



    </div>
    <div class="form-group col-lg-7">

        <label for="name" class="col-lg-2 labelwidth ">From Date<span style="color:red">*</span></label>

        <div class="col-lg-3" style="    padding-left:0px;">
            <input type="text" name="FromDate" id="txtFromDate" class=" form-control" />
        </div>

        <label for="name" class="col-lg-2">To Date<span style="color:red">*</span></label>

        <div class="col-lg-3">
            <input type="text" name="ToDate" id="txtToDate" class="inputclass form-control" />
        </div>
    </div>

    <div class="form-group col-lg-5">
        <br /><br />
    </div>

    <div class="form-group" style="margin-top:10px;">
        <header class="panel-heading">
            <b>
                Design form for mobile application.
            </b>
        </header>



        <div class="col-lg-2" style="min-height: 150px; border: 1px solid #ccc; padding-left: 0px; padding-right: 0px;
                                                        margin-left: 6px; padding-left: 0px; margin-top: 7px; margin-bottom: 10px;">
            <div>
                <div class="row" style="margin-right: 0px; margin-left: 0px; height: 37px;">
                    <div id="divCustmizedContainer">
                        <div class="panel panel-default">

                            <div class="panel-heading">
                                <b class="panel-title" style="font-weight:700; padding-left:6px;">Section </b>
                                <div class="btn-group pull-right" style="top: -5px; margin-right: 5px;">
                                    <button type="submit" id="btnAddCustomized" title="Add New Section" class="btn btn-default btn-sm btn-flied">
                                        <i class="fa fa-plus-square" style="font-size: 14px;color: #47a447;"></i>
                                    </button>
                                    <button type="submit" id="btnDeleteCustomized" title="Delete Section" class="btn btn-default btn-sm btn-flied">
                                        <i class="fa fa-times" style="font-size: 14px;color: #d2322d;"></i>
                                    </button>
                                    <button type="submit" id="btnCopyCustomized" title="Copy Section" class="btn btn-default btn-sm btn-flied">
                                        <i class="fa fa-clipboard" style="font-size: 14px;"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="fieldChooser" class="col-lg-5" style="width:43%;">



            @*Source Fields  min-height: 380px; max-height: 380px;*@

            <div id="sourceFields" style="float: left; width: 48%; float: left; margin: 5px; overflow-y: scroll !important; min-height: 300px; border: 1px solid #ccc; ">
                <header class=" panel-heading" style="background-color: #6cbff7; color: #fff;">
                    <b>
                        Source Fields.
                    </b>
                </header>
            </div>

            @*Drag and drop the source fields in below box.*@


            <div id="destinationFields" style="float: right; width: 49%; float: left; margin: 5px 2px; min-height: 300px; overflow-y: scroll !important; border: 1px solid #ccc; ">
                <header class="panel-heading" style="background-color: #6cbff7; color:#fff;">
                    <b>
                        Field For Current Section.
                    </b>
                </header>
            </div>

        </div>

        <div class="col-lg-4" style="min-height: 300px; border: 1px solid #ccc; padding-left: 0px; padding-right: 0px; float: left;
         margin-left: 6px; padding-left: 0px; margin-top: 7px; margin-bottom: 10px;">
            <div>
                <div class="row" style="margin-right: 0px; margin-left: 0px;">

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <b class="panel-title" style="font-weight:700; padding-left:6px;">Set Field</b>
                            <div class="btn-group " style="top: -5px; margin-right: 5px;" id="childPartialDiv">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="form-group">
    <div class="col-lg-12" style="text-align:right">
        <button id="btnSubmitForm" class="btn btn-success" type="button">Submit</button>
        <button id="btnBackForm" class="btn btn-success" type="button">Back</button>
    </div>
</div>


<div class="modal fade modal-dialog-center" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content-wrap">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Set Section Name</h4>
                </div>
                <div class="modal-body">
                    <div class="panel-body">
                        <form id="form3" class="cmxform form-horizontal tasi-form">
                            <div class="form-group">
                                <label for="name" class="col-lg-3">Section Name <span style="color:red">*</span></label>
                                <div class="col-lg-3">
                                    <input type="hidden" id="txtDivName" />
                                    <input type="text" name="sectionName" id="txtsectionName" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnSaveSection" class="btn btn-success" type="button">Save</button>
                    <button id="btnCancelSection" class="btn btn-danger" type="button">Cancel</button>
                    <button id="btnResetSection" class="btn btn-default" type="button">Reset</button>
                </div>
            </div>
        </div>
    </div>
</div>



<link href="~/Scripts/js/style_management.css" rel="stylesheet" />
<link href="~/Scripts/js/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/js/jquery-ui.js"></script>
<script src="~/Scripts/js/fieldChooser.js"></script>


<link href="~/Content/MSTS/admin/css/bootstrap-multiselect.css" rel="stylesheet" />
<script src="~/Content/MSTS/admin/js/bootstrap-multiselect.js"></script>

GarronT.CMS.UI/Areas/Admin/Views/Form/_FormHome.cshtml
<div class="adv-table">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-xs-4 add_newbtn">
            <a class="btn btn-success" id="btnAddForm" data-toggle="modal" data-backdrop="static">
                Add New <i class="fa fa-plus"></i>
            </a>
        </div>
        <div class="col-lg-8 col-md-8 col-xs-8 show_deactive deactivated_records">
            <input type="checkbox" name="showDeactivate" id="chkShowDeactivate" />Show Deactivated Records
        </div>
    </div>
    <table id="dynamic-table" class="display table table-bordered table-striped dataTable" aria-describedby="dynamic-table_info">
        <thead>
            <tr>
                <th width="15%">City</th>
                <th width="20%">Client Name</th>
                <th width="15%">Project Name</th>
                <th width="15%">Form Name</th>
                <th width="12%">From Date</th>
                <th width="12%">To Date</th>
                <th width="23%">Action</th>
            </tr>
        </thead>


    </table>
</div>

<!-- Modal for Add /Edit Dialog -->
<!-- modal -->
<!-- Modal for deactivation -->
<div class="modal fade modal-dialog-center" id="confirmDeactivatedialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content-wrap">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Default Modal Title</h4>
                </div>
                <div class="modal-body">

                    <input type="hidden" id="deactivationID" />
                    <p>Are you sure to deactivate this record ?</p>

                </div>
                <div class="modal-footer">
                    <button id="btnDeactivateYes" class="btn btn-success" type="button">Yes</button>
                    <button class="btn btn-danger" id="btnDeactivatNo" type="button">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- modal -->
<!-- Modal for confirmActivatedialog -->
<div class="modal fade modal-dialog-center" id="confirmActivatedialog" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content-wrap">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Default Modal Title</h4>
                </div>
                <div class="modal-body">


                    <input type="hidden" id="activationID" />
                    <p>Are you sure to Activate this record ?</p>


                </div>
                <div class="modal-footer">
                    <button id="btnActivateYes" class="btn btn-success" type="button">Yes</button>
                    <button class="btn btn-danger" id="btnActivatNo" type="button">No</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
           
        
        var actualDate = new Date();
        var newDate = new Date(actualDate.getFullYear(), actualDate.getMonth() - 1, actualDate.getDate());
        $("#btnAddForm").click(function () {
            debugger;
            $("#divLandingPage").empty();

            var urlgetFormPartial = $('#getFormPartial').val();
            $.ajax({
                url: urlgetFormPartial,
                type: "GET",
                async: false,
                success: function (data) {
                    $("#divLandingPage").append(data);
                }
            });


            $('#txtFromDate').datepicker({
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                dateFormat: 'dd MM yy',
            }).datepicker("setDate", newDate);


            $('#txtToDate').datepicker({
                changeMonth: true,
                changeYear: true,
                showButtonPanel: true,
                dateFormat: 'dd MM yy',
            }).datepicker("setDate", actualDate);


            
            var urlStateData = $('#GetProjectList').val();
            $.ajax({
                type: 'POST',
                url: urlStateData,
                success: function (data) {

                    $('#ddlProject').empty();

                    $.each(data, function (index, item) {
                        if (index == 0) {
                            $('#ddlProject').append(
                              $('<option></option>').val('0').html("--Select Project--"));

                        }


                        $('#ddlProject').append(
                               $('<option></option>').val(item.ProjectId).html(item.ProjectName)
                         );
                    });
                         
                },
                error: function () {
                    alert("something seems wrong");
                }
            });

        })


    });




</script>

GarronT.CMS.UI/Areas/Admin/Views/Form/_setField1.cshtml
<div class="row" style="margin-right: 0%; margin-left: 0%; margin-top:0%; float:left; ">

    <div id="dySingleText" style="width: 261px;">
        <div class="panel panel-default">


            <div class="form-group" style=" margin: 5px;">
                <label class="control-label">Field Name</label>

                <input type="text" name="TextLabel" class="form-control" />
            </div>

            <div class="form-group" style=" margin: 5px;">
                <label class="control-label">Data Type</label>

                <input type="text" name="TextLabel" class="form-control" />
            </div>

            <div class="form-group" style=" margin: 5px;">
                <label class="control-label">Hint Text</label>

                <input type="text" name="TextLabel" class="form-control" />
            </div>

            <div class="form-group" style=" margin: 5px;">
                <input type="checkbox" name="Required" id="chkRequired" />
                <label for="chkRequired">Required</label>

                <input type="checkbox" name="Enforce" id="chkEnforceMinMax" />
                <label for="chkEnforceMinMax">Enforce Min/Max</label>
            </div>

            <div class="form-group" style=" margin: 5px;">
                <label class="control-label">Minimum Length</label>

                <input type="text" name="TextLabel" class="form-control" />
            </div>

            <div class="form-group" style=" margin: 5px;">
                <label class="control-label">Maximum Length</label>
                <input type="text" name="TextLabel" class="form-control" />
            </div>

            <br />
        </div>
    </div>

</div>